name: Build

on:
    workflow_run:
        workflows: ["Lint & Test"]
        branches:
            - main
        types:
            - completed

jobs:
    build:
        if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'
        name: Build & Push
        runs-on: ubuntu-latest

        env:
            REGISTRY_BASE: 573962674131.dkr.ecr.us-west-2.amazonaws.com

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to AWS ECR
              uses: docker/login-action@v1
              with:
                  registry: ${{ env.REGISTRY_BASE }}
                  username: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: false
                  # cache-from: type=registry,ref=${{ env.REGISTRY_BASE }}/recipes:latest
                  cache-to: type=inline
                  tags: ${{ env.REGISTRY_BASE }}/recipes:latest